### ISSUE TITLE
chown on docker startup takes a lot of time

### ISSUE THREAD

**Issue by cortho** [owncloud-docker/base#82]
Currently, because of find .. chown, docker startup takes several minutes - only for this step - whereas the rest of the setup is quite fast. (see
https://github.com/owncloud-docker/base/blob/master/rootfs/etc/owncloud.d/25-chown.sh)

Is there a chance to speed up this process? Is chown -R an option?

**Comment by tboerger** [comment]
There is no other way to speed it up, the `find` approach is the fastest option, `chown -R` is much slower than the `find` approach, that's why it had been done like that.

If you really know what you are doing you could define the env variable `OWNCLOUD_SKIP_CHOWN` with `true` as a value, but if something breaks because of permissions I'm out of supporting it.
